export const UserDatasDuplicate = [
    {
        id: '121',
        first_name: 'John',
        last_name: 'Doe',
        dob: '2020-10-01',
        mobile: '+1-1234567890',
        address: '123 Main St',
        city: 'Anytown',
        state: 'California',
        occupation: 'Engineer',
        gender: 'male',
        blood_group: 'A+',
        profile: null,
        age: 42,
        marital_status: 'married',
        email_id: 'john.doe@example.com'
    },
    {
        id: '123',
        first_name: 'Jane',
        last_name: 'Smith',
        dob: '2020-10-01',
        mobile: '+44-9876543210',
        address: '456 Elm St',
        city: 'Smallville',
        state: 'Kansas',
        occupation: 'Doctor',
        gender: 'female',
        blood_group: 'B-',
        profile: null,
        age: 32,
        marital_status: 'single',
        email_id: 'jane.smith@example.com'
    },
    {
        id: '163',
        first_name: 'Michael',
        last_name: 'Johnson',
        dob: '2020-10-01', mobile: '+61-7418529630',
        address: '789 Oak St',
        city: 'Metroville',
        state: 'New York',
        occupation: 'Lawyer',
        gender: 'male',
        blood_group: 'AB+',
        profile: '',
        age: 36,
        marital_status: 'single',
        email_id: 'michael.johnson@example.com'
    },
    {
        id: '145',
        first_name: 'Emily',
        last_name: 'Brown',
        dob: '2020-10-01', mobile: '+33-3692581470',
        address: '101 Pine St',
        city: 'Greenville',
        state: 'Texas',
        occupation: 'Teacher',
        gender: 'female',
        blood_group: 'O-',
        profile: '',
        age: 27,
        marital_status: 'married',
        email_id: 'emily.brown@example.com'
    },
    {
        id: '556',
        first_name: 'David',
        last_name: 'Lee',
        dob: '2020-10-01', mobile: '+91-9876543210',
        address: '222 Cedar St',
        city: 'Springfield',
        state: 'Illinois',
        occupation: 'Artist',
        gender: 'male',
        blood_group: 'A-',
        profile: '',
        age: 49,
        marital_status: 'divorced',
        email_id: 'david.lee@example.com'
    },
    {
        id: '63',
        first_name: 'Emma',
        last_name: 'Garcia',
        dob: '2020-10-01', mobile: '+61-1234567890',
        address: '333 Maple St',
        city: 'Riverside',
        state: 'California',
        occupation: 'Dentist',
        gender: 'female',
        blood_group: 'B+',
        profile: '',
        age: 33,
        marital_status: 'single',
        email_id: 'emma.garcia@example.com'
    },
    {
        id: '17',
        first_name: 'James',
        last_name: 'Martinez',
        dob: '2020-10-01', mobile: '+44-7418529630',
        address: '444 Oak St',
        city: 'Hill Valley',
        state: 'California',
        occupation: 'Architect',
        gender: 'male',
        blood_group: 'AB-',
        profile: '',
        age: 51,
        marital_status: 'married',
        email_id: 'james.martinez@example.com'
    },
    {
        id: '82',
        first_name: 'Olivia',
        last_name: 'Taylor',
        dob: '2020-10-01', mobile: '+1-3692581470',
        address: '555 Elm St',
        city: 'Sunnydale',
        state: 'California',
        occupation: 'Writer',
        gender: 'female',
        blood_group: 'O+',
        profile: '',
        age: 39,
        marital_status: 'single',
        email_id: 'olivia.taylor@example.com'
    },
    {
        id: '93',
        first_name: 'Alexander',
        last_name: 'Rodriguez',
        dob: '2020-9-01', mobile: '+33-9876543210',
        address: '666 Pine St',
        city: 'Oceanview',
        state: 'Florida',
        occupation: 'Engineer',
        gender: 'male',
        blood_group: 'A-',
        profile: '',
        age: 30,
        marital_status: 'single',
        email_id: 'alexander.rodriguez@example.com'
    },
    {
        id: '10',
        first_name: 'Sophia',
        last_name: 'Lopez',
        dob: '2018-5-01', mobile: '+91-1234567890',
        address: '777 Cedar St',
        city: 'Hollywood',
        state: 'California',
        occupation: 'Actor',
        gender: 'female',
        blood_group: 'B-',
        profile: '',
        age: 34,
        marital_status: 'divorced',
        email_id: 'sophia.lopez@example.com'
    },
    {
        id: '113',
        first_name: 'William',
        last_name: 'Harris',
        dob: '2020-10-01', mobile: '+61-7418529630',
        address: '888 Maple St',
        city: 'Bayview',
        state: 'New Jersey',
        occupation: 'Manager',
        gender: 'male',
        blood_group: 'AB+',
        profile: null,
        age: 43,
        marital_status: 'married',
        email_id: 'william.harris@example.com'
    },
    {
        id: '124',
        first_name: 'Isabella',
        last_name: 'Young',
        dob: '2020-10-01', mobile: '+44-3692581470',
        address: '999 Oak St',
        city: 'Riverdale',
        state: 'New York',
        occupation: 'Nurse',
        gender: 'female',
        blood_group: 'O-',
        profile: '',
        age: 37,
        marital_status: 'single',
        email_id: 'isabella.young@example.com'
    },
    {
        id: '162',
        first_name: 'Praba',
        last_name: 'D',
        dob: '2020-10-01', mobile: '+91-7458693212',
        address: '45, Orleanpet, Pondy',
        city: 'Puducherry',
        state: 'Pondicherry',
        occupation: 'Software Engineer',
        gender: 'male',
        blood_group: 'A1+ve',
        profile: "",
        age: 29,
        marital_status: 'single',
        email_id: 'prabaidymoto@gmail.com'

    },
    {
        id: '174',
        first_name: 'Ava',
        last_name: 'Martinez',
        dob: '2020-10-01', mobile: '+33-7418529630',
        address: '222 Oak St',
        city: 'Sunset Valley',
        state: 'Arizona',
        occupation: 'Designer',
        gender: 'female',
        blood_group: 'B+',
        profile: null,        age: 39,
        marital_status: 'married',
        email_id: 'ava.martinez@example.com'
    },
    {
        id: '152',
        first_name: 'Noah',
        last_name: 'Thompson',
        dob: '2020-10-01', mobile: '+61-3692581470',
        address: '333 Elm St',
        city: 'Hillside',
        state: 'Illinois',
        occupation: 'Scientist',
        gender: 'male',
        blood_group: 'AB-',
        profile: null,        age: 30,
        marital_status: 'single',
        email_id: 'noah.thompson@example.com'
    },
    {
        id: '192',
        first_name: 'Mia',
        last_name: 'Nguyen',
        dob: '2020-10-01', mobile: '+44-1234567890',
        address: '444 Maple St',
        city: 'Milltown',
        state: 'California',
        occupation: 'Chef',
        gender: 'female',
        blood_group: 'O+',
        profile: '',
        age: 33,
        marital_status: 'single',
        email_id: 'mia.nguyen@example.com'
    },
    {
        id: '1532',
        first_name: 'Liam',
        last_name: 'Kim',
        dob: '2020-10-01',        mobile: '+1-9876543210',
        address: '555 Cedar St',
        city: 'Springville',
        state: 'Colorado',
        occupation: 'Athlete',
        gender: 'male',
        blood_group: 'A+',
        profile: '',
        age: 45,
        marital_status: 'divorced',
        email_id: 'liam.kim@example.com'
    },
    {
        id: '18154',
        first_name: 'Charlotte',
        last_name: 'Wong',
        dob: '2020-10-01', mobile: '+33-7418529630',
        address: '666 Oak St',
        city: 'Lakewood',
        state: 'Ohio',
        occupation: 'Entrepreneur',
        gender: 'female',
        blood_group: 'B-',
        profile: '',
        age: 35,
        marital_status: 'single',
        email_id: 'charlotte.wong@example.com'
    },
    {
        id: '1945',
        first_name: 'Logan',
        last_name: 'Morgan',
        dob: '2020-10-01', mobile: '+91-3692581470',
        address: '777 Elm St',
        city: 'Greenwood',
        state: 'Mississippi',
        occupation: 'Pilot',
        gender: 'male',
        blood_group: 'AB+',
        profile: '',
        age: 31,
        marital_status: 'single',
        email_id: 'logan.morgan@example.com'
    },
    {
        id: '2024',
        first_name: 'Amelia',
        last_name: 'Jones',
        dob: '2020-10-01', mobile: '+61-1234567890',
        address: '888 Maple St',
        city: 'Hillside',
        state: 'New Jersey',
        occupation: 'Psychologist',
        gender: 'female',
        blood_group: 'O-',
        profile: '',
        age: 39,
        marital_status: 'married',
        email_id: 'amelia.jones@example.com'
    },
    {
        id: '1945',
        first_name: 'Logan',
        last_name: 'Morgan',
        dob: '2020-10-01', mobile: '+91-3692581470',
        address: '777 Elm St',
        city: 'Greenwood',
        state: 'Mississippi',
        occupation: 'Pilot',
        gender: 'male',
        blood_group: 'AB+',
        profile: '',
        age: 31,
        marital_status: 'single',
        email_id: 'logan.morgan@example.com'
    },
    {
        id: '2024',
        first_name: 'Amelia',
        last_name: 'Jones',
        dob: '2020-10-01', mobile: '+61-1234567890',
        address: '888 Maple St',
        city: 'Hillside',
        state: 'New Jersey',
        occupation: 'Psychologist',
        gender: 'female',
        blood_group: 'O-',
        profile: '',
        age: 39,
        marital_status: 'married',
        email_id: 'amelia.jones@example.com'
    },
    {
        id: '192',
        first_name: 'Mia',
        last_name: 'Nguyen',
        dob: '2020-10-01', mobile: '+44-1234567890',
        address: '444 Maple St',
        city: 'Milltown',
        state: 'California',
        occupation: 'Chef',
        gender: 'female',
        blood_group: 'O+',
        profile: '',
        age: 33,
        marital_status: 'single',
        email_id: 'mia.nguyen@example.com'
    },
    {
        id: '1532',
        first_name: 'Liam',
        last_name: 'Kim',
        dob: '2020-10-01', mobile: '+1-9876543210',
        address: '555 Cedar St',
        city: 'Springville',
        state: 'Colorado',
        occupation: 'Athlete',
        gender: 'male',
        blood_group: 'A+',
        profile: '',
        age: 45,
        marital_status: 'divorced',
        email_id: 'liam.kim@example.com'
    },
]